"use client";

const labCards = [
  { company: "StockIQ", state: "Ready to review", title: "Benchmark execution and entitlements", next: "Review the cited benchmark and decide the package implication.", due: "Today", priority: "high", className: "is-review" },
  { company: "GovWorx", state: "Waiting on Kevin", title: "Obtain the GovWorx product demo", next: "Ask Kevin to provide or schedule the demo; no delivery is proven yet.", due: "Overdue", priority: "normal", className: "is-waiting" },
  { company: "Avionté", state: "Needs reconciliation", title: "Confirm launch readiness evidence", next: "Reconcile the new implementation update against the current milestone.", due: "Jul 24", priority: "high", className: "is-reconciliation" },
];

const navigation = ["Open Work", "Mail", "Calendar", "Projects", "Documents", "Transcripts", "Notes", "Companies", "Search", "Learning & sources"];

export function UILab({ onClose }: { onClose: () => void }) {
  return (
    <section className="ui-lab" aria-labelledby="ui-lab-title">
      <header className="ui-lab-hero"><div><span className="eyebrow">COMMAND CENTER UI SYSTEM · V1</span><h2 id="ui-lab-title">Executive clarity, evidence close at hand</h2><p>A fixture-only gallery for the deterministic ledger and CEO intelligence shadow. Nothing here reads or changes live work.</p></div><button type="button" className="button-secondary" onClick={onClose}>Back to Learning</button></header>

      <section className="lab-section"><header><span>01</span><div><h3>Foundations</h3><p>Typography, spacing, surfaces, and semantic color.</p></div></header><div className="token-grid"><article><span>TYPE</span><strong className="token-display">Business meaning first</strong><p>28 / 20 / 16 / 14 / 12</p></article><article><span>SPACE</span><div className="space-scale"><i /><i /><i /><i /><i /></div><p>4 · 8 · 12 · 20 · 32</p></article><article><span>SURFACES</span><div className="surface-scale"><i /><i /><i /></div><p>Canvas · paper · raised</p></article><article><span>SEMANTIC</span><div className="semantic-scale"><i className="fresh" /><i className="waiting" /><i className="reconcile" /><i className="danger" /></div><p>Fresh · waiting · reconcile · risk</p></article></div></section>

      <section className="lab-section"><header><span>02</span><div><h3>Collapsed commitments</h3><p>What, next, when, and owner/blocker in one scan.</p></div></header><div className="lab-card-stack">{labCards.map((card) => <article className={`lab-work-card ${card.className}`} key={card.title}><button className="lab-check" type="button" aria-label={`Mark ${card.title} done`}><i /></button><button className="lab-card-open" type="button" aria-label={`Open ${card.title}`}><span className="lab-card-meta"><b>{card.company}</b><em>{card.state}</em></span><strong>{card.title}</strong><p><b>Next</b>{card.next}</p><span className="lab-card-end">{card.priority === "high" ? <em>High</em> : null}<time>{card.due}</time></span></button></article>)}</div></section>

      <section className="lab-section lab-two-column"><div><header><span>03</span><div><h3>Direct controls</h3><p>Quiet, deterministic, and reversible.</p></div></header><div className="control-gallery"><button type="button">Done</button><button type="button" className="button-secondary">Waiting on…</button><label>Due date<input type="date" defaultValue="2026-07-24" /></label><label>Priority<select defaultValue="high"><option>normal</option><option>high</option></select></label><div className="inline-receipt" role="status"><span>Marked done.</span><button type="button">Undo</button></div><p className="field-error">Add a named dependency before marking this Waiting.</p></div></div><div><header><span>04</span><div><h3>Semantic states</h3><p>Business state and evidence state stay distinct.</p></div></header><div className="chip-gallery"><span className="semantic-chip chip-open">Open</span><span className="semantic-chip chip-waiting">Waiting on Kyle</span><span className="semantic-chip chip-review">Ready to review</span><span className="semantic-chip chip-reconciliation">Needs reconciliation</span><span className="semantic-chip chip-fresh">Evidence fresh</span><span className="semantic-chip chip-stale">Evidence stale</span></div></div></section>

      <section className="lab-section"><header><span>05</span><div><h3>CEO Read and connected evidence</h3><p>Attributable intelligence that never overwrites the ledger silently.</p></div></header><article className="lab-ceo-read"><header><div><span className="eyebrow">CEO READ · SHADOW</span><h3>The demo is still an unmet external dependency</h3></div><span className="semantic-chip chip-reconciliation">New evidence</span></header><div className="lab-ceo-grid"><div><span>Recommended next move</span><strong>Ask Kevin to provide or schedule the product demo before the fact-base analysis begins.</strong></div><dl><div><dt>Owner / dependency</dt><dd>GovWorx · Kevin</dd></div><div><dt>Done when</dt><dd>A reviewable demo or recording is linked as delivered evidence.</dd></div></dl></div><div className="lab-evidence-row"><span>SUPPORTS</span><strong>Approved kickoff deck · Product demo commitment</strong><em>Fresh 2d ago</em></div><div className="lab-evidence-row"><span>INFORMS</span><strong>Hugo secret-shopping scope</strong><em>Fresh today</em></div></article></section>

      <section className="lab-section lab-two-column"><div><header><span>06</span><div><h3>System states</h3><p>Useful recovery language, not technical noise.</p></div></header><div className="system-state-grid"><article><i className="state-spinner" /><strong>Refreshing evidence</strong><p>Cached work remains available.</p></article><article><i className="state-stale" /><strong>Evidence may be stale</strong><p>Last verified 8 days ago.</p></article><article><i className="state-offline" /><strong>Source offline</strong><p>The ledger is safe; retry the source later.</p></article><article><i className="state-error" /><strong>Could not save</strong><p>No change was applied.</p></article></div></div><div><header><span>07</span><div><h3>Workspace navigation</h3><p>One visual grammar across every source surface.</p></div></header><nav className="lab-navigation" aria-label="UI lab navigation patterns">{navigation.map((item, index) => <button className={index === 0 ? "active" : ""} type="button" key={item}><i />{item}{index < 3 ? <kbd>{index + 1}</kbd> : null}</button>)}</nav></div></section>

      <section className="lab-section"><header><span>08</span><div><h3>Expanded-card hierarchy</h3><p>Meaning and next move lead; controls, evidence, working area, and audit follow.</p></div></header><div className="expanded-card-map"><article className="map-primary"><span>01</span><div><strong>Business meaning + next move</strong><p>The commitment and definition of done.</p></div></article><article><span>02</span><div><strong>Direct controls + current state</strong><p>Quiet fields with verified inline receipts.</p></div></article><article><span>03</span><div><strong>CEO Read</strong><p>Shadow judgment, relationships, and freshness.</p></div></article><article><span>04</span><div><strong>Evidence + working area</strong><p>Sources and the type-aware place to work.</p></div></article><article><span>05</span><div><strong>History</strong><p>Collapsed technical audit trail.</p></div></article></div></section>
    </section>
  );
}
